name: asurascans_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Medium.ttf
          weight: 400
        - asset: fonts/FiraSans-Regular.ttf
          weight: 500
